create table product_info
(
    sku                           VARCHAR(8) PRIMARY KEY,
    upc                           TEXT                      NOT NULL,
    style_number                  TEXT                      NOT NULL,
    department_number             TEXT                      NOT NULL,
    subdepartment_number          TEXT                      NOT NULL,
    class_number                  TEXT                      NOT NULL,
    subclass_number               TEXT                      NOT NULL,
    vendor_number                 TEXT                      NOT NULL,
    map                           NUMERIC(20, 2),
    npip                          NUMERIC(20, 2),
    bm_discountable               BOOLEAN,
    dsg_ecomm_discountable        BOOLEAN,
    gg_ecomm_discountable         BOOLEAN,
    fs_ecomm_discountable         BOOLEAN,
    pl_ecomm_discountable         BOOLEAN,
    web_ready                     BOOLEAN,
    dsg_web_ready                 BOOLEAN,
    gg_web_ready                  BOOLEAN,
    fs_web_ready                  BOOLEAN,
    pl_web_ready                  BOOLEAN,
    dsg_min_quantity              INTEGER,
    gg_min_quantity               INTEGER,
    fs_min_quantity               INTEGER,
    pl_min_quantity               INTEGER,
    dsg_max_quantity              INTEGER,
    gg_max_quantity               INTEGER,
    fs_max_quantity               INTEGER,
    pl_max_quantity               INTEGER,
    dsg_sale_item_exclusions      BOOLEAN,
    gg_sale_item_exclusions       BOOLEAN,
    fs_sale_item_exclusions       BOOLEAN,
    pl_sale_item_exclusions       BOOLEAN,
    dsg_promotion_exclusion_group INTEGER,
    gg_promotion_exclusion_group  INTEGER,
    fs_promotion_exclusion_group  INTEGER,
    pl_promotion_exclusion_group  INTEGER,
    insert_timestamp              TIMESTAMPTZ DEFAULT now() NOT NULL,
    added_by                      TEXT                      NOT NULL,
    last_modified_timestamp       TIMESTAMPTZ DEFAULT now() NOT NULL,
    last_modified_by              TEXT                      NOT NULL,
    status                        VARCHAR(1)                NOT NULL
);