---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: nexus.tools.dcsg.com:5003/dcsg-pricing/ci-build-jdk11
    tag: 0.1

inputs:
  - name: git

outputs:
  - name: build-output

run:
  path: entrypoint.sh
  args:
    - bash
    - -ceux
    - git/ci/build.sh